"""Encrypted storage primitive — SQLCipher wrapper for sensitive tables.

Replaces v2's flawed `age + sqlite` design. SQLCipher encrypts at the page
level so normal transactional writes work without decrypt/reencrypt cycles.

Usage:
    with EncryptedDB.open("/opt/compai/state/subjects.db.enc") as db:
        db.execute("SELECT ...")

The encryption key lives in /opt/compai/credentials/storage.key (mode 600,
generated by install.sh on first boot). Rotating the key requires dumping and
reloading — out of scope for v0.4.

We fall back to sqlite3 with a soft warning if sqlcipher3 is unavailable, so
smoke tests can run in CI without the native dep. In production `install.sh`
installs the sqlcipher library and the Python binding.
"""
from __future__ import annotations
import os
import secrets
import sys
from contextlib import contextmanager
from pathlib import Path

try:
    from sqlcipher3 import dbapi2 as _sqlite  # type: ignore
    ENCRYPTED = True
except ImportError:
    import sqlite3 as _sqlite  # type: ignore
    ENCRYPTED = False

DEFAULT_KEY_PATH = Path(os.environ.get("COMPAI_HOME", "/opt/compai")) / "credentials" / "storage.key"


def ensure_key(key_path: Path = DEFAULT_KEY_PATH) -> str:
    """Return the storage key, generating it if missing."""
    if not key_path.exists():
        key_path.parent.mkdir(parents=True, exist_ok=True)
        key_path.write_text(secrets.token_hex(32))
        os.chmod(key_path, 0o600)
    return key_path.read_text().strip()


class EncryptedDB:
    """Thin wrapper around an encrypted SQLite connection."""

    def __init__(self, path: Path | str, key: str | None = None):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._key = key or ensure_key()
        self.conn = _sqlite.connect(str(self.path))
        if ENCRYPTED:
            self.conn.execute(f"PRAGMA key = '{self._key}'")
        self.conn.execute("PRAGMA journal_mode = WAL")
        self.conn.execute("PRAGMA foreign_keys = ON")
        self.conn.row_factory = _sqlite.Row
        os.chmod(self.path, 0o600)

    def execute(self, sql: str, *args):
        return self.conn.execute(sql, args[0] if args and isinstance(args[0], (list, tuple, dict)) else args)

    def executemany(self, sql: str, rows):
        return self.conn.executemany(sql, rows)

    def executescript(self, sql: str):
        return self.conn.executescript(sql)

    def commit(self):
        self.conn.commit()

    def close(self):
        try:
            self.conn.close()
        except Exception:
            pass

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type is None:
                self.commit()
        finally:
            self.close()


@contextmanager
def open_db(path: Path | str, schema_sql: str | None = None):
    db = EncryptedDB(path)
    try:
        if schema_sql:
            db.executescript(schema_sql)
            db.commit()
        yield db
    finally:
        db.close()


def encryption_status() -> str:
    return "SQLCipher (page-level)" if ENCRYPTED else "plaintext (dev/test only — install sqlcipher3 for prod)"


if __name__ == "__main__":
    print(f"compai_init.ingest.storage — {encryption_status()}", file=sys.stderr)
